### ISSUE TITLE
Numpy error in github

### ISSUE THREAD

**Issue by JaimePSantos** [den01-python-programming-exercises/exercise-2-2-square-root-of-sum-JaimePSantos#1]
Hello,
I have the numpy library installed locally, all the tests pass but github gives me this error
  E   ModuleNotFoundError: No module named 'numpy'

**Comment by Scott3142** [comment]
That's my error - I hadn't included the `pip install numpy` line in the workflow.yml file for this exercise. 

You can fix it for this repo by adding `pip install numpy` above/below the `pip install flake8` line in the workflow.yml file (in .github/workflows/workflow.yml) and re-committing. 

That'll make it pass the Python tests but it'll still fail the Github Classroom workflow until I update the base repo which I'll do now.
